
## Default port.
#server.port.http: 8080

## add HTTPS
#server.port: 8443
#security.require-ssl: true
#server.ssl.key-store: /path/to/letsencrypt/mysite.com/keystore.p12
#server.ssl.key-store-password: myPassword
#server.ssl.keyStoreType: PKCS12
#server.ssl.keyAlias: tomcat

## Database
spring.datasource.url: jdbc:mysql://localhost:3306/oneshot?useSSL=true
spring.datasource.username: oneshot
spring.datasource.password: oneshot
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

## for crossorigin
front.url: http://localhost:3000

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: update

stripe.public.key: pk_test_j0a9nVTLFSIv54y8OP5JlFm7
stripe.private.key: sk_test_esi8MMImEX3RJpMjnR9bvRt5
