---
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url: jdbc:mysql://localhost:3306/oneshot?useSSL=false
spring.datasource.username: oneshot
spring.datasource.password: oneshot
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
front.url: http://127.0.0.1:8081

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: update
#12 hours
#server.session.timeout=43200

---
spring.profiles: prod

front.url: monurl.com

