## add HTTPS
server.port: 8443
security.require-ssl: true
server.ssl.key-store: /path/to/letsencrypt/mysite.com/keystore.p12
server.ssl.key-store-password: myPassword
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat

## Database
spring.datasource.url: jdbc:mysql://localhost:3306/oneshot?useSSL=false
spring.datasource.username: oneshot
spring.datasource.password: oneshot
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

## for crossorigin
front.url: front.url

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: update

stripe.public.key: stripe_public_key
stripe.private.key: stripe_private_key
